### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by SandeshGC** [Ankit-11525/e-commerce_redstore.github.io#10]
Hi, @Ankit-11525 ! According to these statements, I think you should add "hacktoberfest" tag to the repo or, label this repo as "hacktoberfest-accepted".
And, you should add "hacktoberfest-accepted" label to the merged PRs.

![image](https://user-images.githubusercontent.com/59115123/193409313-96686f16-20da-4dab-9fdb-34010eff73fe.png)

**Comment by Ankit-11525** [comment]
okay done !!

**Comment by SandeshGC** [comment]
@Ankit-11525  may I suggest displaying price as: "Rs. 590" instead of "590 Rs." ?

**Comment by Ankit-11525** [comment]
Yeah great!! Go for it

**Comment by Ankit-11525** [comment]
Hope , the hacktoberfest label and topic was resolved !

**Comment by SandeshGC** [comment]
Yes it was, thank you. I will create an issue for the price indication. But I have another issue first.
