### ISSUE TITLE
Back-To-Top Button 

### ISSUE THREAD

**Issue by Jyotiraditya24** [Ankit-11525/e-commerce_redstore.github.io#106]
**Describe the bug**
Back to top button in mobile view gets underneath the images

**To Reproduce**
1. Go to responsive mode mobile view
3. Scroll down to see button underneath the images

**Expected behavior**
the Back-To-Button should be above the images

**Screenshots**
<img width="760" alt="Screenshot 2022-10-10 at 4 05 17 AM" src="https://user-images.githubusercontent.com/93746326/194782686-ef6a70e6-438f-42be-a360-29cc3ed683a3.png">

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [chrome]

**Comment by Jyotiraditya24** [comment]
if you could assign me this issue , I like to contribute

**Comment by Ankit-11525** [comment]
please have a review in issue section that nobody is working on this same issue

**Comment by Jyotiraditya24** [comment]
@Ankit-11525 I , had a review nobody is working on this issue before me

**Comment by Jyotiraditya24** [comment]
this issue was resolved in #116
