### ISSUE TITLE
Add Snackbar/Toast when a Product is Added to Cart or Removed from Cart.

### ISSUE THREAD

**Issue by Rohitprasad83** [Ankit-11525/e-commerce_redstore.github.io#110]
**Is your feature request related to a problem? Please describe.**
Whenever a product is added or removed from the cart, the user has no visual feedback.

**Describe the solution you'd like**
A Snackbar/Toast would be helpful to give the user feedback that the product is added or removed from the cart.

**Comment by Rohitprasad83** [comment]
Can you please assign this to me and add hacktoberfest labels. Thanks

**Comment by Ankit-11525** [comment]
Yeah sure ! Go for it

**Comment by Rohitprasad83** [comment]
I am working on this.

**Comment by Ankit-11525** [comment]
@rushiikudapane  Please find another problem on this project .
Hope you find and Please raise a issue.
