### ISSUE TITLE
scroll to top btn also visible on hero section

### ISSUE THREAD

**Issue by Dharmik3** [Ankit-11525/e-commerce_redstore.github.io#112]
**Describe the bug**
The scroll to top btn is visible on hero section or landing page.And btn also having overlapping problem in responsive screen

**Expected behavior**
When we open the site on the hero section the scroll to top btn should not be visible and after scrolling that section this btn should be visible.And I will also fixed the srollToTop btn image overlapping problem.

**Screenshots**

<img width="1440" alt="Screenshot 2022-10-10 at 1 28 25 PM" src="https://user-images.githubusercontent.com/78194918/194821723-9e6c355b-a630-4b90-9e07-130099eef172.png">

<img width="409" alt="Screenshot 2022-10-10 at 12 54 25 PM" src="https://user-images.githubusercontent.com/78194918/194821800-a2c8322c-dd03-43ed-8fa0-9cd62d4db7f9.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome 
 - Browser Version [105.0.5195.125]

**Comment by Ankit-11525** [comment]
I guess somebody is already working on it , Please have review on issue section of this project

**Comment by Dharmik3** [comment]
Issue#106 in which only overlapping problem will be solved and I would like to implement both visibility of scrollToTop btn after the hero section and overlapping of element.

**Comment by Jyotiraditya24** [comment]
@Dharmik3 are you still seeing the overlapping issue in your browser?

**Comment by Dharmik3** [comment]
hello @Jyotiraditya24 now it's fixed overlapping issue.

**Comment by Jyotiraditya24** [comment]
yes @Dharmik3 I closed my issue

**Comment by Ankit-11525** [comment]
So i think this issue should be close.
