### ISSUE TITLE
No notification after add to cart

### ISSUE THREAD

**Issue by tiosetiawan** [Ankit-11525/e-commerce_redstore.github.io#136]
**Describe the bug**
No notification after add to cart

<img width="940" alt="swal to cart" src="https://user-images.githubusercontent.com/34486747/195290718-e1ce2f90-0285-4559-bd29-6969852f6ce0.png">

**Solution**
added sweet alert notify after submit

please allow me to add a notification alert after adding a product to cart

@Ankit-11525

**Comment by Abhay5855** [comment]
Can you assign me this issue I can work on it @tiosetiawan

**Comment by Ankit-11525** [comment]
Already done ! please review the website
