### ISSUE TITLE
Dark mode not properly applied

### ISSUE THREAD

**Issue by AditiSingh2003** [Ankit-11525/e-commerce_redstore.github.io#137]
**Describe the bug**
In dark mode offer section has some area where dark mode is not applied 

**Expected behavior**
The section will be completely black. That will give a nice effect and combined effect in website.

**Screenshots**
<img width="960" alt="container " src="https://user-images.githubusercontent.com/97729662/195291504-40b0db3a-c5d5-4488-8708-31e6485c6a3c.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**

**Comment by JatinSingh08** [comment]
Hey @AditiSingh2003, Can you please assign this issue to me. I would love to work on this.

**Comment by Ankit-11525** [comment]
Sure go ahead!
