### ISSUE TITLE
Links not present in brands section

### ISSUE THREAD

**Issue by rtewari056** [Ankit-11525/e-commerce_redstore.github.io#15]
There should a link attached to the brand names.

**Comment by Ankit-11525** [comment]
Please explain much more

**Comment by rtewari056** [comment]
#### Basically, there is a brands section on the website (as you can see in the screenshot) where you can find brand names and there should be a link attached with the logo so that when a user clicks on them it will redirect to the actual website of the brand

![brands](https://user-images.githubusercontent.com/75976169/193421299-0c89765a-d513-43dc-aecd-516434d4f534.png)

**Comment by Ankit-11525** [comment]
okay go for it !
