### ISSUE TITLE
sun icon is visible under the toggle ball.

### ISSUE THREAD

**Issue by MahendraBishnoi29** [Ankit-11525/e-commerce_redstore.github.io#150]
**Describe the bug**
sun icon is visible under toggle ball also the position is also should be `right: 2px`

**To Reproduce**
1. switch to light mode
2. see the visible icon

**Expected behavior**
it should be completely hidden

**Screenshots**
<img width="50" alt="Screenshot 2022-10-14 075442" src="https://user-images.githubusercontent.com/74294202/195748979-38dd9ff9-3a86-418c-868c-d28b84a3ce30.png">

**Comment by Ankit-11525** [comment]
Please share corrected screenshot
