### ISSUE TITLE
Product details are sticky to image in cart page.

### ISSUE THREAD

**Issue by MahendraBishnoi29** [Ankit-11525/e-commerce_redstore.github.io#152]
**Describe the bug**
product details are sticky to image

**To Reproduce**
1. Go to cart
2. see the product image and info

**Expected behavior**
there should be some gap between image and info

**Screenshots**
<img width="302" alt="Screenshot 2022-10-14 082021" src="https://user-images.githubusercontent.com/74294202/195751424-77fac93b-4911-40ef-981f-36a9e006676a.png">

**Screenshot after my changes**
<img width="378" alt="Screenshot 2022-10-14 081944" src="https://user-images.githubusercontent.com/74294202/195751296-7df06947-7eac-4760-bee0-eb9cdf748d10.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome

**Additional context**

**Comment by MahendraBishnoi29** [comment]
@Ankit-11525 please assign to me and add hacktoberfest 2022 label so i can submit a PR.

**Comment by Ankit-11525** [comment]
okay go for it!

**Comment by MahendraBishnoi29** [comment]
@Ankit-11525 I've participated in hactoberfest 2022. in My prev PR you didn't added hacktoberfest label 😭.

**Comment by Ankit-11525** [comment]
which PR?

**Comment by MahendraBishnoi29** [comment]
> which PR?

last one where i solved issue #150

**Comment by Ankit-11525** [comment]
PR not issue?

**Comment by MahendraBishnoi29** [comment]
> PR not issue?

https://github.com/Ankit-11525/e-commerce_redstore.github.io/pull/154
