### ISSUE TITLE
Explore now and buy now button does nothing.. I can work on it.

### ISSUE THREAD

**Issue by nishtha53** [Ankit-11525/e-commerce_redstore.github.io#16]

**Comment by Ankit-11525** [comment]
Yeah sure!!
Go ahead->

**Comment by nishtha53** [comment]
Explore now and buy now should redirect to the products page.

**Comment by Ankit-11525** [comment]
okay change it . I have already assigned

**Comment by nishtha53** [comment]
I have changed how can i do PR

**Comment by Ankit-11525** [comment]
just create new pull request button next to issue button
then i'll merge it

**Comment by nishtha53** [comment]
I have created a new branch and tried to push but permission was denied.

**Comment by nishtha53** [comment]
@Ankit-11525 Please check I have created pull request
