### ISSUE TITLE
I want to add  Right-to-Left Color Swap Link Hover Effect in the top most icons i.e home,product,about,contact,account.

### ISSUE THREAD

**Issue by abhay-raj19** [Ankit-11525/e-commerce_redstore.github.io#168]
**I want to add  Right-to-Left Color Swap Link Hovering  Effect in the right top  bar**
    The link starts in one color without an underline. Then, on hover, 
    a new color slides in from the right while an underline slides in from the left.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/96302417/196032568-9a4e1b20-2c49-4b22-a9a4-b3e1809eb7cb.png">

After adding the right to left hovering effect it would look more fantastic and awesome .

![link-underline-to-button-animation-on-hover](https://user-images.githubusercontent.com/96302417/196034774-ad4d593c-be30-4757-8afd-5886cc3e9e82.gif)

Pls assign me i will do my best.
and pls label it with hacktoberfest, i am starting  with my first contribution in the open source community.

**Comment by Ankit-11525** [comment]
sure!
