### ISSUE TITLE
Need README for better understanding about the project

### ISSUE THREAD

**Issue by Ankit-11525** [Ankit-11525/e-commerce_redstore.github.io#2]

**Comment by atom540** [comment]
hey, can you please assign this to me?

**Comment by Ankit-11525** [comment]
yeah sure ! Go ahead..

**Comment by SandeshGC** [comment]
Hi, I am new to hacktoberfest. Is this still available? Can I work on this too?

**Comment by Ankit-11525** [comment]
Hey ! , I have already assigned to other user .
So hope you find any bug , enhancement in this project for which you can raise issue ,after that  i will assign that issue to you .
