### ISSUE TITLE
Changing the display format of price from "999 Rs." to "Rs. 999" and fixing the use of '$' instead of 'Rs.' in the single product page.

### ISSUE THREAD

**Issue by SandeshGC** [Ankit-11525/e-commerce_redstore.github.io#23]
Generally, we use "Rs. 999" instead of using "999 Rs." to indicate the price.
Also, in the single product page there is '$' instead of 'Rs.' 
![image](https://user-images.githubusercontent.com/59115123/193421779-0d623abe-7d55-4784-acb7-1d1d4cdd562a.png)

I would like to work on this issue.

**Comment by Ankit-11525** [comment]
Done!!

**Comment by SandeshGC** [comment]
Hey there! I am working on another issue. Why did you close this one?

**Comment by Ankit-11525** [comment]
oh sorry i think you had fixed this issue.

**Comment by SandeshGC** [comment]
No, I haven't created the PR. I am working on the cart issue.
