### ISSUE TITLE
Add icons and social media links to social media pages 

### ISSUE THREAD

**Issue by YatharthaRana** [Ankit-11525/e-commerce_redstore.github.io#32]
<img width="1390" alt="Screenshot 2022-10-02 at 01 09 54" src="https://user-images.githubusercontent.com/95047694/193425635-744cd923-f5f7-4635-8351-cfeaf1f2ff03.png">

I will add icons before the statement like Facebook Twitter etc

**Comment by Ankit-11525** [comment]
yeah go for it!

**Comment by YatharthaRana** [comment]
@Ankit-11525 Please if you have merged my pull request then close this issue :)
