### ISSUE TITLE
Add pointer to buttons 

### ISSUE THREAD

**Issue by Mohasin-Haque** [Ankit-11525/e-commerce_redstore.github.io#45]
I want to work on buttons as there expected behaviour is not natural. I would like to make pointers in buttons.

**Comment by Ankit-11525** [comment]
yeah sure go for it !!
take care of all button...

**Comment by Mohasin-Haque** [comment]
@Ankit-11525 Fixed the issue, Please check the PR raised. Thank You

**Comment by Ankit-11525** [comment]
done!!
