### ISSUE TITLE
Feature: Hover feature for Latest Products and Featured Products Section

### ISSUE THREAD

**Issue by prakhar-1005** [Ankit-11525/e-commerce_redstore.github.io#50]
The products mentioned in the  Featured Products and Latest Products sections have no hover feature. This makes the site feel less responsive for the user.

I would like to add hover feature to all the products in the Featured Products and Latest Products sections which will enhance the overall user experience.

Screenshots:
![Screenshot (12)_LI](https://user-images.githubusercontent.com/94559623/193559761-74114860-2079-4376-a4af-a01be32ba4b7.jpg)

![Screenshot (13)_LI](https://user-images.githubusercontent.com/94559623/193559773-7b9759bb-cec0-416b-9b10-1d933ecebb39.jpg)

**Comment by Aarav238** [comment]
Please assign this issue to me . I can add hover

**Comment by Ankit-11525** [comment]
okay Go for it!

**Comment by Aarav238** [comment]
Okay.I Will update you by tommorow.
