### ISSUE TITLE
Alignment of links in navbar is a bit off

### ISSUE THREAD

**Issue by SandeshGC** [Ankit-11525/e-commerce_redstore.github.io#6]
This is how the links are aligned right now:
![how it is](https://user-images.githubusercontent.com/59115123/193403895-e5716912-4867-4c5e-b2a2-a9e13db5162e.png)

This is how I think they should look like:
![how it should be](https://user-images.githubusercontent.com/59115123/193403955-5048df0e-cc0d-495f-adb3-9869a5367ded.png)

Do you want me to create a pull request for this? If you think this issue is valid, add the hacktoberfest labels and assign it to me.

**Comment by Ankit-11525** [comment]
yeah sure !!
