### ISSUE TITLE
Cart page with size information

### ISSUE THREAD

**Issue by nayyyhaa** [Ankit-11525/e-commerce_redstore.github.io#60]
**Description**
While adding the same product(with the same size) to the cart, it's creating a duplicate entry on the cart page with no size information.

**Solution**
1) We can update the `productQuantity` when the same item is added (only when id and productSize are the same)
For eg, if the cart has: Shirt with 1 Qty, -> after adding the same product -> it'll update the quantity to 2.
2) Will be adding product size info on the card page, to distinguish between two similar products.

**Additional context**
Screenshot of current scenario
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/46138150/193778522-cb396f32-d4d7-4b57-a2ec-8bacdb8210f1.png">

**Comment by Ankit-11525** [comment]
okay sure , Go ahead!

**Comment by nayyyhaa** [comment]
> okay sure , Go ahead!

Thanks created PR #62
