### ISSUE TITLE
Social media icons not aligned properly 

### ISSUE THREAD

**Issue by kunaaal13** [Ankit-11525/e-commerce_redstore.github.io#63]
**Describe the bug**
The social media icons in the footer are not aligned properly.

**Expected behavior**
The social media icons must be aligned in a line.

**Screenshots**
![Screenshot_2022-10-04-21-44-12-68_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/84015751/193871805-5244c85f-7d7e-4d65-93bf-79364e7b4f45.jpg)

I'd like to work on this issue.

**Comment by Ankit-11525** [comment]
yes sure !! go for it

**Comment by kunaaal13** [comment]
I'm working on this

**Comment by SandeshGC** [comment]
Hey @kunaaal13 , while you're working on this, have a look at the shape of the icons, they are not circle. I think circular icons would be better.

**Comment by kunaaal13** [comment]
hey @SandeshGC I've submitted my pr you can create a new issue and fix that if you want

**Comment by SandeshGC** [comment]
Okay. But if this issue is fixed, please close it.
