### ISSUE TITLE
Add Theme changer

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Ankit-11525/e-commerce_redstore.github.io#67]

**Comment by Beast61224** [comment]
give it to me

**Comment by Beast61224** [comment]
can i have it

**Comment by Codebat-man** [comment]
please assign it to me

**Comment by Ankit-11525** [comment]
![image](https://user-images.githubusercontent.com/76417084/195173289-2a413e68-19db-49bf-ac08-284aedfafb96.png)
theme changer already in website so i'm closing this issue
