### ISSUE TITLE
Add Hover transition in all product.

### ISSUE THREAD

**Issue by Aarav238** [Ankit-11525/e-commerce_redstore.github.io#76]
On hovering on the product Image , transition will take place. 
This will enhance the website . It will attract the attention of the user.
![before ](https://user-images.githubusercontent.com/95538627/193906501-2970d55d-8b52-4a14-acf1-3190152f97ac.png)

I can do this quickly .
Please assign this issue to me.
@Ankit-11525

**Comment by Ankit-11525** [comment]
Is this your second same issue?

**Comment by Aarav238** [comment]
I thought first one was had some problem and there are also some extra line of code . So can i work on this issue again??
@Ankit-11525

**Comment by Ankit-11525** [comment]
yes

**Comment by Aarav238** [comment]
I already worked in this product but it is still open and PR is merged but it is not showing on Hacktoberfest dashboard. 
@Ankit-11525 Please look what happened.
