### ISSUE TITLE
social icons indentation is not proper in footer

### ISSUE THREAD

**Issue by Dharmik3** [Ankit-11525/e-commerce_redstore.github.io#86]
**Describe the bug**
Social icons in footer having not proper indentation , and it's mashup the look and feel of the site , so I can fixed that issue ,please assign that issue to me.

**Screenshots**
<img width="1440" alt="Screenshot 2022-10-07 at 9 50 58 AM" src="https://user-images.githubusercontent.com/78194918/194469219-095ba7de-c086-447f-86b0-4a7b31d8eda7.png">

**Comment by Ankit-11525** [comment]
Already resolved
