### ISSUE TITLE
Improving the Hover effect of follow us icons

### ISSUE THREAD

**Issue by tushar54594** [Ankit-11525/e-commerce_redstore.github.io#91]
* When we hover over any social media icons, it displays  a black and white theme. 

* I will change the hover effect such that when we hover over a particular follow us icon, it will change it's color to it's standard color. Like when we hover over the facebook icon it will change to color to the original color of the facebook logo.  Similarly I will do this for all other icons. This will make the footer look even better.

Screenshot: 
![Screenshot (601)](https://user-images.githubusercontent.com/94536522/194728597-29e2501d-0cf1-47eb-9426-5d8d5eb0e01c.png)

@Ankit-11525 Hey ankit! Please assign me this issue. I will be contributing to this for hacktoberfest

**Comment by SandeshGC** [comment]
This issue is similar to #69

**Comment by Ankit-11525** [comment]
It is already assigned

**Comment by tushar54594** [comment]
Ok! Then I'll close this
