### ISSUE TITLE
Adding Scroll up button functionality on Home page

### ISSUE THREAD

**Issue by rushikesh1799** [Ankit-11525/e-commerce_redstore.github.io#92]
**Is your feature request related to a problem? Please describe.**
The Home page of the website is a little long like 5-6 scrolls. After we go down completely it takes the same amount of time to come up which is not a good user experience.

**Describe the solution you'd like**
Our website should have a scroll-up button that would take website visitors directly to the top of the page.

**Additional context**
As you can see, I have created one button on the bottom right corner, once clicked it would take you to the top of the page.
![image](https://user-images.githubusercontent.com/68096217/194735713-7d29399b-23f2-428e-a671-cada9240ef57.png)

**Comment by rushikesh1799** [comment]
Can you please assign this to me so that I will check the code and Submit PR? Also please add the hacktoberfest labels. Thanks

**Comment by Ankit-11525** [comment]
okay done!

**Comment by rushikesh1799** [comment]
#94 - Submitted PR. Please review and merge it. Also, let me know if there are any issues. Thanks.
