### ISSUE TITLE
The hover effects on products is excessive.

### ISSUE THREAD

**Issue by SandeshGC** [Ankit-11525/e-commerce_redstore.github.io#93]
When we hover on the displayed products, there is a nice scaling effect. But this effect is a bit excessive and takes a lot of space. Also, this effect should not be used in screens with small sizes.

On hover:
![image](https://user-images.githubusercontent.com/59115123/194740535-e2549f1b-4159-4247-8305-e114057b42e6.png)

I suggest reducing the scale of the products, or just scaling up the image of the product, while keeping the container unscaled.

**Comment by Ankit-11525** [comment]
yes its amazing to see changes !

**Comment by SandeshGC** [comment]
What do you think about this change? @Ankit-11525 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/59115123/194768483-9dc9b60b-e854-4c9c-9b73-74c1c1562ddb.gif)

**Comment by Ankit-11525** [comment]
It's very cool

**Comment by SandeshGC** [comment]
This issue has been fixed buy #118
