### ISSUE TITLE
Modify the text in the testimonial section

### ISSUE THREAD

**Issue by tushar54594** [Ankit-11525/e-commerce_redstore.github.io#96]
* In the What our Customers say section, the reviews given are some random texts which are generated by the user. 

* This does not look good 

* I will add proper and meaningful reviews for all the 3 customers in the testimonial section. 

![Screenshot (607)](https://user-images.githubusercontent.com/94536522/194755645-417f2c2f-8756-4264-87d5-1bfb457f42dc.png)

Hey @Ankit-11525 Please assign me this issue.

**Comment by Ankit-11525** [comment]
Thats Great!

**Comment by Ankit-11525** [comment]
Go for it!

**Comment by tushar54594** [comment]
Hey @Ankit-11525 I made the required changes. Kindly review my PR

**Comment by Ayushbajpai19** [comment]
Can I work on it, i would like to add additional testimonials in this section please

**Comment by Ankit-11525** [comment]
@Ayushbajpai19 can you create another issue for this and please describe your idea
