### ISSUE TITLE
Useful Links at the bottom aren't working as links, they are normal texts.

### ISSUE THREAD

**Issue by nihshesh** [Ankit-11525/e-commerce_redstore.github.io#98]
Please assign me this issue.
![image](https://user-images.githubusercontent.com/61341935/194757276-ccfe0461-b315-48b7-82c9-6437e5433ebb.png)

**Comment by gajanansr** [comment]
assign this to me

**Comment by Abhay5855** [comment]
Can you assing me this issue? @nihshesh

**Comment by Ankit-11525** [comment]
Okay go for it!

**Comment by nihshesh** [comment]
I can see it is already fixed.
